apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: my-web-app-py-docker
  name: my-web-app-py-docker
  namespace: my-webapp
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'my-web-app-py:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/SanthoshBabuMR/flask-hello-world-docker.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'ubuntu:16.04'
    type: Docker
  